[package]
name = "chase/darwin"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
DataServiceTyped = "leifstout/dataservicetyped@1.0.5"

[server-dependencies]